Repository ezsystems/ezplatform-http-cache, pull requests merged in 2019-08, with the labels that each got.

#96 EZP-30814: Removed Twig deprecations
  src/Resources/views/fields/content_fields.html.twig
Labels: Improvement

#95 EZP-30662: Added http cache tests
  .travis.yml
  behat_suites.yml
  features/symfony/cache.feature
  features/view_cache_tags.feature
Labels: Ready for MERGE

#97 EZP-30814: Fixed extra %} in content_fields.html.twig
  src/Resources/views/fields/content_fields.html.twig
Labels: Bug

#98 EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls
  src/DependencyInjection/Configuration.php
Labels: Improvement, QA approved

#92 EZP-30544: Refactored to use FOSHttpCache default ResponseHeader
  src/AppCache.php
  src/DependencyInjection/EzPlatformHttpCacheExtension.php
  src/EventSubscriber/UserContextSubscriber.php
  src/Resources/config/default_settings.yml
  src/Resources/config/fos_http_cache.yml
  src/Resources/config/services.yml
  src/Resources/config/view_cache.yml
Labels: Improvement

#94 EZP-30544: Use default user hash header name
  docs/fos_http_cache.md
  docs/varnish/vcl/varnish5.vcl
  src/AppCache.php
  src/EventSubscriber/RequestEventSubscriber.php
  src/Resources/config/fos_http_cache.yml
  src/Resources/config/view_cache.yml
Labels: QA approved

#93 EZP-30544: Use FOS default TagHeader and Purge Method for Varnish
  docs/varnish/README.md
  docs/varnish/vcl/parameters.vcl
  docs/varnish/vcl/varnish4.vcl
  docs/varnish/vcl/varnish5.vcl
  src/DependencyInjection/Compiler/VarnishCachePass.php
  src/EzSystemsPlatformHttpCacheBundle.php
  src/ProxyClient/Varnish.php
  src/Resources/config/fos_http_cache.yml
  src/Resources/config/services.yml
Labels: QA approved
