Repository ezsystems/ezplatform-http-cache, pull requests merged in 2020-02, with the labels that each got.

#106 EZP-31113: AssignSectionToSubtreeSignal is not handled by search and HTTP cache
  src/Resources/config/slot.yml
  src/SignalSlot/SectionService/AssignSectionToSubtreeSlot.php
Labels: Bug, QA approved

#114 [Travis] Changed user running REST tests to root
  .travis.yml
Labels: Ready for review

#119 EZP-30560: Unable to clear Varnish cache on Platform.sh
  src/PurgeClient/VarnishPurgeClient.php
Labels: QA approved
