Repository ezsystems/ezplatform-http-cache, pull requests merged in 2020-03, with the labels that each got.

#118 [3.x][VCL] Update purge logic from FOS
  docs/varnish/vcl/varnish5.vcl
Labels: QA approved

#113 EZP-30562: As an Dev/Administrator I would like to use short HTTP cache tags
  composer.json
  docs/using_tags.md
  docs/varnish/README.md
  docs/varnish/vcl/varnish5.vcl
  spec/EventSubscriber/RestKernelViewSubscriberSpec.php
  spec/EventSubscriber/UserContextSubscriberSpec.php
  spec/EventSubscriber/XLocationIdResponseSubscriberSpec.php
  spec/Handler/TagHandlerSpec.php
  spec/RepositoryTagPrefixSpec.php
  spec/ResponseTagger/Value/ContentInfoTaggerSpec.php
  spec/ResponseTagger/Value/LocationTaggerSpec.php
  src/EventSubscriber/CachePurge/AbstractSubscriber.php
  src/EventSubscriber/CachePurge/ContentEventsSubscriber.php
  src/EventSubscriber/CachePurge/ContentTypeEventsSubscriber.php
  src/EventSubscriber/CachePurge/LocationEventsSubscriber.php
  src/EventSubscriber/CachePurge/SectionEventsSubscriber.php
  src/EventSubscriber/CachePurge/UserEventsSubscriber.php
  src/EventSubscriber/RestKernelViewSubscriber.php
  src/EventSubscriber/XLocationIdResponseSubscriber.php
  src/Handler/ContentTagInterface.php
  src/Handler/TagHandler.php
  src/PurgeClient/RepositoryPrefixDecorator.php
  src/RepositoryTagPrefix.php
  src/Resources/config/services.yml
  src/Resources/config/view_cache.yml
  src/Resources/views/fields/content_fields.html.twig
  src/ResponseTagger/Value/ContentInfoTagger.php
  src/ResponseTagger/Value/LocationTagger.php
  src/Twig/ContentTaggingExtension.php
  tests/PurgeClient/LocalPurgeClientTest.php
  tests/PurgeClient/RepositoryPrefixDecoratorTest.php
  tests/PurgeClient/VarnishPurgeClientTest.php
Labels: QA approved

#107 EZP-31113: AssignSectionToSubtree event is not handled by search and HTTP cache
  src/EventSubscriber/CachePurge/LocationEventsSubscriber.php
  src/EventSubscriber/CachePurge/SectionEventsSubscriber.php
Labels: Bug, QA approved

#121 EZP-31220: Migrated codebase to Symfony 5
  composer.json
  phpspec.yml
  spec/EventSubscriber/HiddenLocationExceptionSubscriberSpec.php
  spec/EventSubscriber/HttpCacheResponseSubscriberSpec.php
  spec/EventSubscriber/RestKernelViewSubscriberSpec.php
  spec/EventSubscriber/UserContextSubscriberSpec.php
  spec/EventSubscriber/XLocationIdResponseSubscriberSpec.php
  spec/ResponseConfigurator/ConfigurableResponseCacheConfiguratorSpec.php
  src/EventSubscriber/HiddenLocationExceptionSubscriber.php
  src/Handler/TagHandler.php
  tests/ContextProvider/RoleIdentifyTest.php
  tests/PurgeClient/LocalPurgeClientTest.php
  tests/PurgeClient/RepositoryPrefixDecoratorTest.php
  tests/PurgeClient/VarnishPurgeClientTest.php
Labels: Ready for MERGE

#124 Restored FOS header and separator override for local purge type
  src/DependencyInjection/EzPlatformHttpCacheExtension.php
Labels: Bug

#125 EZP-31007: Replaced ezpublish-kernel with ezplatform-kernel
  README.md
  composer.json
Labels: Improvement
